

const mongoose = require('mongoose');
let Schema = mongoose.Schema;

let SchoolSchema = new Schema({
  ALABAMA: Number,
  ALASKA: Number,
  ARIZONA: Number,
  ARKANSAS: Number,
  CALIFORNIA: Number,
  COLORADO: Number,
  CONNECTICUT: Number,
  DELAWARE: Number,
  DISTRICT_OF_COLUMBIA: Number,
  FLORIDA: Number,
  GEORGIA: Number,
  HAWAII: Number,
  IDAHO: Number,
  ILLINOIS: Number,
  INDIANA: Number,
  IOWA: Number,
  KANSAS: Number,
  KENUTCKY: Number,
  LOUISIANA: Number,
  MAINE: Number,
  MARYLAND: Number,
  MASSACHUSETTS: Number,
  MICHIGAN: Number,
  MINNESOTA: Number,
  MISSISSIPPI: Number,
  MISOURI: Number,
  MONTANA: Number,
  NEBRASKA: Number,
  NEVADA: Number,
  NEW_HAMPSHIRE: Number,
  NEW_JERSEY: Number,
  NEW_MEXICO: Number,
  NEW_YORK: Number,
  NORTH_CAROLINA: Number,
  NORTH_DAKOTA: Number,
  OHIO: Number,
  OKLAHOMA: Number,
  OREGON: Number,
  PENNSYLVANIA: Number,
  RHODE_ISLAND: Number,
  SOUTH_CAROLINA: Number,
  SOUTH_DAKOTA: Number,
  TENNESSEE: Number,
  TEXAS: Number,
  UTAH: Number,
  VERMONT: Number,
  VIRGINIA: Number,
  WASHINGTON: Number,
  WEST_VIRGINIA: Number,
  WISCONSIN: Number,
  WYOMING: Number,
  UNKNOWN: Number,
  AMERICAN_SAMOA: Number,
  MICRONESIA: Number,
  GUAM: Number,
  MARSHALL_ISLANDS: Number,
  NORTHERN_MARIANAS: Number,
  PALAU: Number,
  PUERTO_RICO: Number,
  VIRGIN_ISLANDS: Number,
  FOREGIN_COUNTRY: Number,
  TOTAL: Number,
  SCHOOL_NAME: String
})

let SchoolModel = mongoose.model('SchoolModel', SchoolSchema);

module.exports = SchoolModel;